@startuml

class Examination{
    //标题
    private String title;
    //细节
    private String detail;
    //作者
    private String author;
    //1:作业 2:考试 3:题库
    private Integer type;
    //教材
    private String textbook;
    //科目
    private String subject;
    //学段
    private String grade;
    private List<Chapter> chapterList;
}

class Chapter{
    @Column //章节名称
    private String name;
    @Column(typeConverter = LongListConverter.class)
    private List questionIds;
    Integer index; //序列
}

Examination o-- Chapter

@enduml