/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_scribble_touch_RawInputProcessor */

#ifndef _Included_com_onyx_android_sdk_scribble_touch_RawInputProcessor
#define _Included_com_onyx_android_sdk_scribble_touch_RawInputProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_scribble_touch_RawInputProcessor
 * Method:    nativeRawReader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_scribble_touch_RawInputProcessor_nativeRawReader
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_android_sdk_scribble_touch_RawInputProcessor
 * Method:    nativeRawClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_scribble_touch_RawInputProcessor_nativeRawClose
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_android_sdk_scribble_touch_RawInputProcessor
 * Method:    nativeSetStrokeWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_scribble_touch_RawInputProcessor_nativeSetStrokeWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_onyx_android_sdk_scribble_touch_RawInputProcessor
 * Method:    nativeSetLimitRegion
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_scribble_touch_RawInputProcessor_nativeSetLimitRegion
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
