/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper */

#ifndef _Included_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
#define _Included_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeInitLibrary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeInitLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeDestroyLibrary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeDestroyLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeOpenDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeOpenDocument
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeCloseDocument
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeCloseDocument
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeMetadata
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeMetadata
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativePageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativePageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativePageSize
 * Signature: (I[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativePageSize
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeRenderPage
 * Signature: (IIIIILandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeRenderPage
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    hitTest
 * Signature: (IIIIIIIII[D)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_hitTest
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeSearchInPage
 * Signature: (I[BZZ)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeSearchInPage
  (JNIEnv *, jobject, jint, jbyteArray, jboolean, jboolean);

/*
 * Class:     com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper
 * Method:    nativeGetPageText
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_onyx_kreader_plugins_pdfium_PdfiumJniWrapper_nativeGetPageText
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
