/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_zip_ZipDecryption */

#ifndef _Included_com_onyx_zip_ZipDecryption
#define _Included_com_onyx_zip_ZipDecryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_zip_ZipDecryption_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_zip_ZipDecryption_open
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_onyx_zip_ZipDecryption_size
  (JNIEnv *, jobject);

/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    seek
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_zip_ZipDecryption_seek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    readContent
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_zip_ZipDecryption_readContent
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_onyx_zip_ZipDecryption
 * Method:    closeZip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_zip_ZipDecryption_closeZip
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
