/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_reader_ReaderImageUtils */

#ifndef _Included_com_onyx_reader_ReaderImageUtils
#define _Included_com_onyx_reader_ReaderImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_reader_ReaderImageUtils
 * Method:    crop
 * Signature: (Landroid/graphics/Bitmap;IIIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_onyx_reader_ReaderImageUtils_crop
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_onyx_reader_ReaderImageUtils
 * Method:    reflowPage
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;Lcom/onyx/reader/ReaderScannedPageReflowManager;Lcom/onyx/reader/ReaderScannedPageReflowSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_reader_ReaderImageUtils_reflowPage
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject);

/*
 * Class:     com_onyx_reader_ReaderImageUtils
 * Method:    emboldenInPlace
 * Signature: (Landroid/graphics/Bitmap;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_reader_ReaderImageUtils_emboldenInPlace
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onyx_reader_ReaderImageUtils
 * Method:    setContrast
 * Signature: (Landroid/graphics/Bitmap;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_reader_ReaderImageUtils_gammaCorrection
  (JNIEnv *, jclass, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
