/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_reader_utils_ImageUtils */

#ifndef _Included_com_onyx_android_sdk_reader_utils_ImageUtils
#define _Included_com_onyx_android_sdk_reader_utils_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_onyx_android_sdk_reader_utils_ImageUtils_NO_GAMMA
#define com_onyx_android_sdk_reader_utils_ImageUtils_NO_GAMMA -1.0f
#undef com_onyx_android_sdk_reader_utils_ImageUtils_MAX_GAMMA
#define com_onyx_android_sdk_reader_utils_ImageUtils_MAX_GAMMA 200.0f
/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    crop
 * Signature: (Landroid/graphics/Bitmap;IIIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_crop
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    emboldenInPlace
 * Signature: (Landroid/graphics/Bitmap;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_emboldenInPlace
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    gammaCorrection
 * Signature: (Landroid/graphics/Bitmap;F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_gammaCorrection
  (JNIEnv *, jclass, jobject, jfloat, jfloatArray);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    reflowPage
 * Signature: (Ljava/lang/String;Landroid/graphics/Bitmap;Lcom/onyx/android/sdk/reader/reflow/ImageReflowSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_reflowPage
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    isPageReflowed
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_isPageReflowed
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    getReflowedPageSize
 * Signature: (Ljava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_getReflowedPageSize
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    renderReflowedPage
 * Signature: (Ljava/lang/String;IIIILandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_renderReflowedPage
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jobject);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    releaseReflowedPages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_releaseReflowedPages
  (JNIEnv *, jclass);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    toRgbwBitmap
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_toRgbwBitmap
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    toColorBitmap
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_toColorBitmap
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_utils_ImageUtils
 * Method:    isValidPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_ImageUtils_isValidPage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
