/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_scribble_utils_InkUtils */

#ifndef _Included_com_onyx_android_sdk_scribble_utils_InkUtils
#define _Included_com_onyx_android_sdk_scribble_utils_InkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_scribble_utils_InkUtils
 * Method:    nativeDrawStroke
 * Signature: (Landroid/graphics/Canvas;Landroid/graphics/Paint;[F)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_scribble_utils_InkUtils_nativeDrawStroke
  (JNIEnv *, jclass, jobject, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
