/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper */

#ifndef _Included_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
#define _Included_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    open
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_open
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    isEncrypted
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_isEncrypted
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    setPassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_setPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    getEntries
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_getEntries
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper
 * Method:    extractEntryData
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_onyx_android_sdk_reader_plugins_comic_UnrarJniWrapper_extractEntryData
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
