/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper */

#ifndef _Included_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
#define _Included_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeOpenFile
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeOpenFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeGotoPage
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeGotoPage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeGetPageSize
 * Signature: (II[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeGetPageSize
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeExtractPageText
 * Signature: (IILjava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeExtractPageText
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeDrawPage
 * Signature: (IILandroid/graphics/Bitmap;FIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeDrawPage
  (JNIEnv *, jobject, jint, jint, jobject, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sdk_reader_plugins_djvu_DjvuJniWrapper_nativeClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
