/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_reader_utils_OnyxDrmUtils */

#ifndef _Included_com_onyx_android_sdk_reader_utils_OnyxDrmUtils
#define _Included_com_onyx_android_sdk_reader_utils_OnyxDrmUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_reader_utils_OnyxDrmUtils
 * Method:    setup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_android_sdk_reader_utils_OnyxDrmUtils_setup
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_onyx_android_sdk_reader_utils_OnyxDrmUtils
 * Method:    decrypt
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_android_sdk_reader_utils_OnyxDrmUtils_decrypt
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
