/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_kreader_plugins_images_ImagesJniWrapper */

#ifndef _Included_com_onyx_kreader_plugins_images_ImagesJniWrapper
#define _Included_com_onyx_kreader_plugins_images_ImagesJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_kreader_plugins_images_ImagesJniWrapper
 * Method:    nativeClearBitmap
 * Signature: (Landroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_images_ImagesJniWrapper_nativeClearBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_onyx_kreader_plugins_images_ImagesJniWrapper
 * Method:    nativePageSize
 * Signature: (Ljava/lang/String;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_images_ImagesJniWrapper_nativePageSize
  (JNIEnv *, jobject, jstring, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
