/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sample_utils_EpdUtils */

#ifndef _Included_com_onyx_android_sample_utils_EpdUtils
#define _Included_com_onyx_android_sample_utils_EpdUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sample_utils_EpdUtils
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_android_sample_utils_EpdUtils_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
