/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_kreader_utils_PdfWriterUtils */

#ifndef _Included_com_onyx_kreader_utils_PdfWriterUtils
#define _Included_com_onyx_kreader_utils_PdfWriterUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    openExistingDocument
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_openExistingDocument
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    createNewDocument
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_createNewDocument
  (JNIEnv *, jclass);

/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    writeHighlight
 * Signature: (ILjava/lang/String;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_writeHighlight
  (JNIEnv *, jclass, jint, jstring, jfloatArray);

/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    writePolyLine
 * Signature: (I[FIF[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_writePolyLine
  (JNIEnv *, jclass, jint, jfloatArray, jint, jfloat, jfloatArray);

/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    saveAs
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_saveAs
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_onyx_kreader_utils_PdfWriterUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onyx_kreader_utils_PdfWriterUtils_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
