/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_libsetting_util_QRCodeUtil */

#ifndef _Included_com_onyx_edu_student_utils_QRCodeUtil
#define _Included_com_onyx_edu_student_utils_QRCodeUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_onyx_edu_student_utils_QRCodeUtil_DEBUG
#define com_onyx_edu_student_utils_QRCodeUtil_DEBUG 0L
/*
 * Class:     com_onyx_einfo_utils_QRCodeUtil
 * Method:    toRgbwBitmap
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_onyx_edu_student_utils_QRCodeUtil_toRgbwBitmap
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
