/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_kreader_plugins_djvu_DjvuJniWrapper */

#ifndef _Included_com_onyx_kreader_plugins_djvu_DjvuJniWrapper
#define _Included_com_onyx_kreader_plugins_djvu_DjvuJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeOpenFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeOpenFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeGotoPage
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeGotoPage
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeGetPageSize
 * Signature: (Ljava/lang/String;I[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeGetPageSize
  (JNIEnv *, jobject, jstring, jint, jfloatArray);

/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeExtractPageText
 * Signature: (Ljava/lang/String;ILjava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeExtractPageText
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeDrawPage
 * Signature: (Ljava/lang/String;Landroid/graphics/Bitmap;FIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeDrawPage
  (JNIEnv *, jobject, jstring, jobject, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_onyx_kreader_plugins_djvu_DjvuJniWrapper
 * Method:    nativeClose
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onyx_kreader_plugins_djvu_DjvuJniWrapper_nativeClose
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
