package com.onyx.android.sdk.scribble.data;

import com.onyx.android.sdk.scribble.utils.ShapeUtils;
import com.raizlabs.android.dbflow.annotation.*;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.util.Date;

/**
 * Created by zhuzeng on 6/21/16.
 * Represent library container and document. When document id is not null, it's a document
 * when library id is not null, it's a library.
 */
@Table(database = ShapeDatabase.class)
public class NoteModel extends BaseModel {

    public static final int TYPE_LIBRARY = 0;
    public static final int TYPE_DOCUMENT = 1;

    @Column
    @PrimaryKey(autoincrement = true)
    @Index
    long id;

    @Column
    Date createdAt = null;

    @Column
    Date updatedAt = null;

    @Column
    @Unique
    String uniqueId;

    @Column
    String parentUniqueId;

    @Column
    String subPageName;

    @Column
    String title;

    @Column
    String extraAttributes;

    @Column
    int type;

    public NoteModel() {
    }

    public long getId() {
        return id;
    }

    public void setId(long value) {
        id = value;
    }

    public void setCreatedAt(final Date d) {
        createdAt = d;
    }

    public final Date getCreatedAt() {
        return createdAt;
    }

    public final Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(final Date d) {
        updatedAt = d;
    }

    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * the unique id can be generated by itself when it's virtual note
     * also it can be md5 of associated file.
     * @param id
     */
    public void setUniqueId(final String id) {
        uniqueId = id;
    }

    public String getParentUniqueId() {
        return parentUniqueId;
    }

    public void setParentUniqueId(final String name) {
        parentUniqueId = name;
    }

    public String getSubPageName() {
        return subPageName;
    }

    public void setSubPageName(final String spn) {
        subPageName = spn;
    }

    public String getExtraAttributes() {
        return extraAttributes;
    }

    public void setExtraAttributes(final String attributes) {
        extraAttributes = attributes;
    }

    public void setTitle(final String id) {
        title = id;
    }

    public String getTitle() {
        return title;
    }

    public int getType() {
        return type;
    }

    public void setType(int t) {
        type = t;
    }

    public boolean isDocument() {
        return type == TYPE_DOCUMENT;
    }

    public boolean isLibrary() {
        return type == TYPE_LIBRARY;
    }

    public static NoteModel createNote(final String parentUniqueId) {
        final NoteModel document = new NoteModel();
        document.setType(TYPE_DOCUMENT);
        document.setUniqueId(ShapeUtils.generateUniqueId());
        document.setParentUniqueId(parentUniqueId);
        return document;
    }

    public static NoteModel createLibrary(final String parentUniqueId, final String title) {
        final NoteModel library = new NoteModel();
        library.setType(TYPE_LIBRARY);
        library.setUniqueId(ShapeUtils.generateUniqueId());
        library.setParentUniqueId(parentUniqueId);
        library.setTitle(title);
        return library;
    }


}
