/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_kreader_utils_ImageUtils */

#ifndef _Included_com_onyx_kreader_utils_ImageUtils
#define _Included_com_onyx_kreader_utils_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_onyx_kreader_utils_ImageUtils_NO_GAMMA
#define com_onyx_kreader_utils_ImageUtils_NO_GAMMA -1.0f
#undef com_onyx_kreader_utils_ImageUtils_STANDARD_GAMMA
#define com_onyx_kreader_utils_ImageUtils_STANDARD_GAMMA 150.0f
#undef com_onyx_kreader_utils_ImageUtils_MAX_GAMMA
#define com_onyx_kreader_utils_ImageUtils_MAX_GAMMA 200.0f
/*
 * Class:     com_onyx_kreader_utils_ImageUtils
 * Method:    crop
 * Signature: (Landroid/graphics/Bitmap;IIIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_onyx_kreader_utils_ImageUtils_crop
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_onyx_kreader_utils_ImageUtils
 * Method:    reflowPage
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;Lcom/onyx/kreader/reflow/ImageReflowManager;Lcom/onyx/kreader/reflow/ImageReflowSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_ImageUtils_reflowPage
  (JNIEnv *, jclass, jobject, jstring, jobject, jobject);

/*
 * Class:     com_onyx_kreader_utils_ImageUtils
 * Method:    emboldenInPlace
 * Signature: (Landroid/graphics/Bitmap;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_ImageUtils_emboldenInPlace
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onyx_kreader_utils_ImageUtils
 * Method:    gammaCorrection
 * Signature: (Landroid/graphics/Bitmap;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onyx_kreader_utils_ImageUtils_gammaCorrection
  (JNIEnv *, jclass, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
