/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_sdk_scribble_utils_Algorithm */

#ifndef _Included_com_onyx_android_sdk_scribble_utils_Algorithm
#define _Included_com_onyx_android_sdk_scribble_utils_Algorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_sdk_scribble_utils_Algorithm
 * Method:    distance
 * Signature: (FFFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_onyx_android_sdk_scribble_utils_Algorithm_distance
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
